---
fixtures:
  repositories:
    stdlib:   "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    iptables: "https://github.com/simp/pupmod-simp-iptables.git"
    simplib:   "https://github.com/simp/pupmod-simp-simplib.git"
    haveged:
      repo : "https://github.com/simp/puppet-haveged.git"
      branch : "simp-master"
  symlinks:
    libreswan: "#{source_dir}"
