HOSTS:
  left:
    roles:
      - server
      - left
      - agent
      - libreswan
      - default
    platform:   el-7-x86_64
    box:        centos/7
    box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-7.2-64-nocm
    hypervisor: vagrant
  right:
    roles:
      - server
      - right
      - agent
      - libreswan
    platform:   el-7-x86_64
    box:        centos/7
    box_url:    https://vagrantcloud.com/puppetlabs/boxes/centos-7.2-64-nocm
    hypervisor: vagrant
CONFIG:
  log_level: verbose
  type:      foss
  vagrant_memsize: 256
  ## vb_gui: true
